export const contact = {
  email: "brytonckober@gmail.com",
  linkedin: "https://www.linkedin.com/in/bryton-k",
};

export const nav = [
  { href: "/", label: "Home" },
  { href: "/case-studies", label: "Case Studies" },
  { href: "/experience", label: "Experience" },
  { href: "/about", label: "About" },
  { href: "/resume", label: "Resume" },
  { href: "/contact", label: "Contact" },
];

export const metrics = [
  { value: "$38M+", label: "omnichannel business supported" },
  { value: "$1M+", label: "Walmart annual run rate in under 6 months" },
  { value: "28+", label: "digital and operational projects delivered" },
  { value: "4", label: "direct reports managed and mentored" },
];

export type CaseStudy = {
  slug: string;
  numeral: string;
  arcana: string;
  title: string;
  overview: string;
  metric?: string;
  challenge: string;
  analysis: string;
  action: string;
  implementation: string;
  result: string;
  role: string;
  goals: string[];
  stakeholders: string[];
  constraints: string[];
  tools: string[];
  risks: string[];
  skills: string[];
  demonstrates: string;
};

export const caseStudies: CaseStudy[] = [
  {
    slug: "pim-implementation",
    numeral: "I",
    arcana: "The Magician",
    title: "Creating one product-data system from many sources",
    overview: "Led the cross-departmental implementation of a Product Information Management system supporting thousands of SKUs across departments and digital channels.",
    metric: "Thousands of SKUs",
    challenge: "Product information had to serve multiple departments and digital channels. Fragmented inputs made consistency, ownership, and scalable execution difficult across a large catalog.",
    analysis: "I gathered cross-departmental requirements and mapped how product data needed to move through the organization and into ecommerce channels. The work required balancing channel needs with shared data standards.",
    action: "I coordinated stakeholders, defined workflows, tracked dependencies and risks, and kept the implementation connected to the operational reality of the teams that would use the system.",
    implementation: "The PIM was introduced as shared infrastructure for thousands of SKUs, with processes designed to improve consistency and support downstream catalog work across digital channels.",
    result: "The organization gained a more scalable foundation for maintaining and distributing product information. The implementation reduced reliance on disconnected sources and created a clearer operating model for future catalog growth.",
    role: "Cross-functional implementation lead",
    goals: ["Centralize product information", "Support multi-channel catalog operations", "Create repeatable product-data workflows"],
    stakeholders: ["Ecommerce", "Product and catalog teams", "Cross-departmental business partners"],
    constraints: ["Thousands of SKUs", "Multiple departmental requirements", "Multiple digital-channel outputs"],
    tools: ["PIM", "Requirements gathering", "Project planning"],
    risks: ["Inconsistent product data", "Workflow adoption", "Channel-specific data requirements"],
    skills: ["Systems implementation", "Product-data governance", "Workflow design", "Stakeholder management"],
    demonstrates: "I can translate fragmented data needs into an implementable system and align the people, processes, and channels around it.",
  },
  {
    slug: "walmart-marketplace",
    numeral: "VII",
    arcana: "The Chariot",
    title: "Scaling a new marketplace channel",
    overview: "Coordinated the commercial and operational workstreams that took Walmart Marketplace from launch to a $1M+ annual run rate in under six months.",
    metric: "$0 → $1M+ run rate",
    challenge: "A new marketplace channel needed enough healthy catalog coverage, competitive pricing, promotional support, reliable fulfillment, and operational discipline to grow quickly without losing control of margin or execution quality.",
    analysis: "I monitored marketplace performance and listing health, evaluated pricing and Buy Box eligibility, and used revenue and margin signals to prioritize the highest-impact work across the catalog.",
    action: "I coordinated catalog expansion, pricing optimization, advertising, promotions, fulfillment, and issue resolution while managing channel P&L and team priorities.",
    implementation: "The channel scaled through coordinated work across marketplace operations and supporting teams, with ongoing KPI reviews used to adjust priorities and protect execution.",
    result: "Walmart Marketplace grew from $0 to a $1M+ annual run rate in under six months across a multi-thousand-SKU catalog.",
    role: "Walmart Marketplace Manager with channel P&L responsibility",
    goals: ["Launch and scale Walmart Marketplace", "Expand healthy catalog coverage", "Improve revenue and margin performance"],
    stakeholders: ["Marketplace team", "Catalog and product-data teams", "Advertising, promotions, and fulfillment partners"],
    constraints: ["New-channel operating model", "Multi-thousand-SKU catalog", "Buy Box, listing-health, and fulfillment requirements"],
    tools: ["Walmart Seller Center", "Walmart Connect", "Looker", "Excel"],
    risks: ["Listing suppression", "Buy Box ineligibility", "Margin pressure", "Fulfillment and inventory constraints"],
    skills: ["Marketplace operations", "P&L management", "Pricing", "Team leadership", "KPI management"],
    demonstrates: "I can turn a marketplace launch into a managed growth system—connecting catalog, commercial, operational, and team execution.",
  },
  {
    slug: "looker-dashboard",
    numeral: "II",
    arcana: "The High Priestess",
    title: "Revealing the story inside marketplace data",
    overview: "Designed a Looker dashboard that consolidated marketplace revenue, margin, and operational KPIs for leadership decision-making.",
    metric: "One leadership view",
    challenge: "Marketplace performance signals were fragmented, making it harder for leadership to see revenue, margin, and operational health in one place.",
    analysis: "I identified the KPIs needed to connect commercial performance with operational execution and organized them around the decisions leaders and marketplace operators needed to make.",
    action: "I built a consolidated Looker view, aligned metric definitions, and structured the reporting so marketplace results could be evaluated across revenue, margin, and operating indicators.",
    implementation: "The dashboard became a shared reporting layer for marketplace performance, giving leadership a consistent way to review trends and direct attention.",
    result: "Leadership gained clearer, consolidated visibility into marketplace revenue, margin, and operational KPIs without relying on disconnected reporting views.",
    role: "Dashboard designer and marketplace subject-matter lead",
    goals: ["Consolidate marketplace reporting", "Clarify KPI definitions", "Support faster, more informed decisions"],
    stakeholders: ["Leadership", "Marketplace operators", "Cross-functional business partners"],
    constraints: ["Multiple marketplace data views", "Different commercial and operational measures"],
    tools: ["Looker", "Excel", "SQL"],
    risks: ["Inconsistent KPI interpretation", "Incomplete cross-channel visibility", "Decision-making from fragmented data"],
    skills: ["KPI design", "Data consolidation", "Revenue and margin analysis", "Executive reporting"],
    demonstrates: "I can translate marketplace data into a decision system that makes complex performance easier to understand and act on.",
  },
  {
    slug: "promotions-ledger",
    numeral: "XIV",
    arcana: "Temperance",
    title: "Aligning promotions across channels",
    overview: "Created a centralized Promotions and Deals Ledger to coordinate promotional activity across Amazon, Walmart, and Shopify.",
    metric: "3 commerce platforms",
    challenge: "Promotional planning was distributed across platforms and teams. Without a shared operating view, timing, ownership, and catalog-wide coverage were harder to coordinate.",
    analysis: "I examined how channel-specific opportunities, dates, products, and owners needed to be represented in one process without erasing important platform differences.",
    action: "I created a shared ledger that standardized promotional planning across Amazon, Walmart, and Shopify and made coverage, timing, and ownership visible.",
    implementation: "The ledger was integrated into the operating rhythm for marketplace and storefront promotions, creating a central reference for planning and follow-through.",
    result: "Teams gained a more consistent way to coordinate promotions, improve catalog-wide coverage, and capture opportunities for non-core SKUs across three platforms.",
    role: "Process designer and cross-channel coordinator",
    goals: ["Centralize promotion planning", "Clarify ownership and timing", "Increase catalog-wide opportunity coverage"],
    stakeholders: ["Amazon, Walmart, and Shopify operators", "Merchandising and promotional partners", "Leadership"],
    constraints: ["Different platform mechanics", "Overlapping calendars", "Large product catalogs"],
    tools: ["Amazon Seller Central", "Walmart Seller Center", "Shopify Plus", "Excel"],
    risks: ["Missed deadlines", "Duplicated work", "Uneven catalog coverage"],
    skills: ["Process standardization", "Cross-channel coordination", "Operational planning", "Adoption"],
    demonstrates: "I build practical systems that turn disconnected channel activity into visible, coordinated execution.",
  },
  {
    slug: "catalog-compliance",
    numeral: "XVI",
    arcana: "The Tower",
    title: "Resolving high-risk marketplace failures",
    overview: "Identified and resolved catalog, variation, suppression, compliance, and brand-conflict issues that could block or limit six- and seven-figure revenue streams.",
    metric: "Six- and seven-figure streams protected",
    challenge: "Complex marketplace defects can surface as lost visibility or selling eligibility while originating in product data, variation structure, brand records, fulfillment settings, or platform policy.",
    analysis: "I triaged issues by revenue exposure, traced symptoms back to likely data or platform causes, documented the evidence, and separated urgent restoration work from longer-term governance needs.",
    action: "I coordinated corrections, platform communication, catalog updates, and follow-through across Amazon US and Canada without exposing confidential case or product details.",
    implementation: "Resolutions were carried through verification, with recurring patterns documented to support more consistent catalog governance and future troubleshooting.",
    result: "High-impact defects were resolved before they could continue blocking or limiting six- and seven-figure revenue streams.",
    role: "Marketplace issue lead and cross-functional coordinator",
    goals: ["Restore listing health", "Protect revenue", "Reduce recurrence through better governance"],
    stakeholders: ["Marketplace and catalog teams", "Internal product-data owners", "Platform support contacts"],
    constraints: ["Platform-controlled workflows", "Confidential product and case information", "Multiple possible root causes"],
    tools: ["Amazon Seller Central", "Catalog-health workflows", "Issue documentation"],
    risks: ["Suppressed listings", "Variation errors", "Brand conflicts", "Compliance defects"],
    skills: ["Root-cause analysis", "Risk prioritization", "Platform communication", "Catalog governance"],
    demonstrates: "I stay composed inside ambiguous platform failures, identify the real operating risk, and coordinate a resolution that protects both revenue and future execution.",
  },
  {
    slug: "accessibility",
    numeral: "XI",
    arcana: "Justice",
    title: "Designing a more accessible digital experience",
    overview: "Proactively identified website accessibility gaps and led cross-functional remediation from assessment through implementation.",
    metric: "Assessment → implementation",
    challenge: "Accessibility gaps created barriers for customers with disabilities and introduced usability and operational risk that needed coordinated attention.",
    analysis: "I identified the gaps, translated them into actionable requirements, and helped teams understand the customer and operational significance of remediation.",
    action: "I coordinated cross-functional owners, tracked remediation work, and kept implementation moving from the initial assessment through delivery.",
    implementation: "Accessibility improvements were incorporated into the website through a structured remediation effort across the relevant teams.",
    result: "The initiative improved website usability for customers with disabilities. No legal compliance certification is claimed.",
    role: "Initiative lead and cross-functional coordinator",
    goals: ["Reduce accessibility barriers", "Translate findings into requirements", "Deliver cross-functional remediation"],
    stakeholders: ["Ecommerce", "Web and technical partners", "Cross-functional business owners"],
    constraints: ["Existing website patterns", "Multiple owners", "Need for practical prioritization"],
    tools: ["Accessibility assessment", "Requirements gathering", "Project tracking"],
    risks: ["Customer usability barriers", "Incomplete remediation", "Unclear ownership"],
    skills: ["Proactive problem identification", "Requirements", "Accessibility coordination", "Implementation leadership"],
    demonstrates: "I recognize operational risk before it becomes a larger problem and can move an important, cross-functional initiative from finding to implementation.",
  },
  {
    slug: "erbellum",
    numeral: "0 → XXI",
    arcana: "The Fool to The World",
    title: "Building and transitioning a DTC brand",
    overview: "Founded and scaled Erbellum, formerly The Broomstick Company, to $200K in revenue before transitioning the business and its operating assets to an acquiring entity.",
    metric: "$200K revenue · customers in 50 states",
    challenge: "Building a direct-to-consumer herb and spice brand required one operator to connect product sourcing, launches, inventory, fulfillment, marketing, customer experience, and a distinct brand system.",
    analysis: "I evaluated product and operating decisions as parts of one system: what could be sourced responsibly, packaged sustainably, communicated clearly, fulfilled reliably, and supported profitably.",
    action: "I created the brand, launched products, managed the ecommerce lifecycle, coordinated inventory and fulfillment, and built a lore-driven solarpunk identity around sustainable packaging.",
    implementation: "The business served customers across all 50 states and generated $200K in revenue. In 2024, I prepared the operation for transition by organizing assets, brand materials, customer data, documentation, and processes.",
    result: "Erbellum was successfully sold and transitioned to an acquiring entity with the operational knowledge and digital assets needed to continue the business.",
    role: "Founder and Ecommerce Manager",
    goals: ["Build a differentiated DTC business", "Operate the end-to-end product lifecycle", "Create a transferable operating system"],
    stakeholders: ["Customers", "Sourcing and fulfillment partners", "Acquiring entity"],
    constraints: ["Founder-led resources", "End-to-end operating responsibility", "Physical product and fulfillment requirements"],
    tools: ["DTC ecommerce", "Inventory and fulfillment workflows", "Brand and customer-experience systems"],
    risks: ["Inventory", "Supplier coordination", "Customer experience", "Transition continuity"],
    skills: ["Entrepreneurship", "Ecommerce operations", "Product launches", "Documentation", "Business transition"],
    demonstrates: "I understand digital operations from both the operator and owner perspectives—and I build processes that remain useful beyond the person who created them.",
  },
  {
    slug: "omnichannel-portfolio",
    numeral: "XXI",
    arcana: "The World",
    title: "Coordinating an omnichannel ecosystem",
    overview: "Supported a $37M–$38M omnichannel business across Amazon, Shopify, and Walmart through catalog operations, reporting, promotions, fulfillment, and issue resolution.",
    metric: "$37M–$38M annual scale",
    challenge: "Amazon, Shopify, and Walmart each impose different catalog, fulfillment, promotion, reporting, and compliance mechanics, while the business still needs coordinated priorities and a coherent customer experience.",
    analysis: "I evaluated channel-specific performance and operating issues in the context of the wider portfolio, prioritizing work by revenue exposure, customer impact, deadlines, and cross-functional dependencies.",
    action: "I coordinated product data, catalog execution, promotions, reporting, fulfillment, and marketplace issue resolution across Amazon US, Amazon Canada, Shopify Plus, and Walmart.",
    implementation: "Shared reporting and planning systems—including marketplace KPI views and a cross-platform promotions ledger—helped connect channel work into a more scalable operating rhythm.",
    result: "The work supported a $37M–$38M omnichannel business, including $22M in Amazon revenue and a $15M Shopify Plus storefront as documented in the source resume.",
    role: "Marketplace and ecommerce operator within a cross-functional portfolio",
    goals: ["Maintain healthy multi-channel execution", "Prioritize operational work at revenue scale", "Improve cross-platform visibility"],
    stakeholders: ["Marketplace and ecommerce teams", "Leadership", "Catalog, fulfillment, and promotional partners"],
    constraints: ["Different platform rules", "Large catalogs", "High revenue exposure", "Concurrent operational priorities"],
    tools: ["Amazon Seller Central", "Shopify Plus", "Walmart Seller Center", "Looker", "Excel"],
    risks: ["Channel-specific defects", "Fragmented reporting", "Promotion conflicts", "Fulfillment constraints"],
    skills: ["Omnichannel operations", "Operational prioritization", "Reporting", "Cross-functional execution"],
    demonstrates: "I can see the whole operating system while still working precisely at the channel, catalog, and issue level.",
  },
  {
    slug: "web-delivery",
    numeral: "A",
    arcana: "The Architect",
    title: "Turning requirements into digital experiences",
    overview: "Coordinated responsive website projects from discovery through development, testing, revision, and launch.",
    challenge: "Client needs had to be translated into clear, functional digital experiences while multiple priorities, revisions, deadlines, and technical issues moved in parallel.",
    analysis: "I clarified requirements, identified implementation constraints, and connected client expectations to practical web decisions.",
    action: "I built and maintained responsive websites, managed revisions and deadlines, tested deliverables, and resolved technical and communication issues.",
    implementation: "Projects moved from requirements gathering through development and testing to launch, with client feedback incorporated throughout delivery.",
    result: "Clients received functional, user-friendly websites delivered through a structured and communicative project process.",
    role: "Web Developer and client delivery partner",
    goals: ["Translate requirements accurately", "Deliver responsive websites", "Manage revisions and deadlines"],
    stakeholders: ["Clients", "Internal delivery partners"],
    constraints: ["Concurrent priorities", "Changing feedback", "Launch deadlines"],
    tools: ["Responsive web development", "Testing", "Requirements gathering"],
    risks: ["Scope ambiguity", "Revision cycles", "Technical defects"],
    skills: ["Client communication", "Technical problem-solving", "Delivery management", "Web development"],
    demonstrates: "My technical fluency is grounded in delivery: understanding the requirement, building the right thing, and carrying it through launch.",
  },
];

export const experience = [
  {
    company: "The Rag Company",
    role: "Walmart Marketplace Manager",
    dates: "2025 – Present",
    summary: "Leads Walmart Marketplace operations, channel performance, team execution, and cross-functional systems initiatives.",
    bullets: [
      "Scaled Walmart Marketplace from $0 to a $1M+ annual run rate in under six months through catalog expansion and pricing optimization.",
      "Led implementation of a PIM system supporting thousands of SKUs across departments and digital channels.",
      "Built a Looker dashboard consolidating marketplace revenue, margin, and operational KPIs for leadership.",
      "Directs Walmart channel P&L across advertising, promotions, pricing, and Buy Box eligibility.",
      "Manages and mentors a team of four while coordinating up to four concurrent cross-functional projects.",
    ],
    tools: ["Walmart Seller Center", "Walmart Connect", "PIM", "Looker", "Excel", "SQL"],
  },
  {
    company: "The Rag Company",
    role: "Ecommerce Specialist",
    dates: "2024 – 2025",
    summary: "Coordinated ecommerce, catalog, reporting, accessibility, and process initiatives across Amazon, Shopify, and Walmart.",
    bullets: [
      "Delivered 28+ digital and operational projects involving reporting systems, catalog migrations, accessibility, and process improvement.",
      "Supported a $37M omnichannel portfolio, including Amazon US and Canada and a $15M Shopify Plus storefront.",
      "Created a cross-platform Promotions and Deals Ledger for Amazon, Walmart, and Shopify.",
      "Resolved catalog and compliance defects that could block or limit six- and seven-figure revenue streams.",
      "Identified website accessibility gaps and led remediation from assessment through implementation.",
    ],
    tools: ["Amazon Seller Central", "Shopify Plus", "GA4", "Excel", "Catalog health", "FBA / FBM"],
  },
  {
    company: "Erbellum (formerly The Broomstick Company)",
    role: "Founder / Ecommerce Manager",
    dates: "2022 – 2024",
    summary: "Founded and operated a direct-to-consumer herb and spice brand, then led its sale and transition.",
    bullets: [
      "Built the business to $200K in revenue and served customers across all 50 states.",
      "Managed sourcing, product launches, ecommerce, inventory, marketing, fulfillment, and customer experience.",
      "Developed a solarpunk-inspired identity with sustainable packaging and lore-driven brand storytelling.",
      "Transitioned digital assets, brand materials, customer data, documentation, and processes to the acquiring entity.",
    ],
    tools: ["DTC ecommerce", "Inventory", "Fulfillment", "Product launches", "Process documentation"],
  },
  {
    company: "Thrive Web Designs",
    role: "Web Developer",
    dates: "2022",
    summary: "Translated client requirements into responsive, user-friendly websites and managed delivery through launch.",
    bullets: [
      "Coordinated projects from requirements gathering through development, testing, and launch.",
      "Managed concurrent client priorities, revisions, and deadlines.",
      "Resolved technical and communication issues throughout delivery.",
    ],
    tools: ["Responsive development", "Requirements gathering", "Testing", "Client delivery"],
  },
  {
    company: "Target",
    role: "Guest Service Specialist",
    dates: "2018 – 2022",
    summary: "Built an early foundation in customer service, issue resolution, and high-volume retail operations.",
    bullets: [],
    tools: ["Customer service", "Retail operations", "Issue resolution"],
  },
];

export const skillGroups = [
  {
    title: "Ecommerce & marketplaces",
    arcana: "The World",
    skills: ["Walmart Seller Center", "Amazon Seller Central", "Shopify Plus / DTC", "Marketplace operations", "Catalog health", "Listing compliance", "Buy Box", "Pricing and promotions", "Marketplace search and ads", "Walmart Connect", "Inventory and fulfillment", "Conversion optimization"],
  },
  {
    title: "Systems & implementation",
    arcana: "The Magician",
    skills: ["PIM", "Platform integrations", "APIs", "Requirements gathering", "Systems implementation", "Process improvement", "Workflow design", "Risk and issue management", "Stakeholder management", "Cross-functional delivery", "Project planning"],
  },
  {
    title: "Analytics & technology",
    arcana: "The High Priestess",
    skills: ["Looker", "Excel", "SQL", "GA4 and attribution", "Revenue forecasting", "Financial modeling", "KPI reporting", "CRM", "HubSpot", "Salesforce", "AI automation", "OpenAI tools"],
  },
];
